POST {{host}}/login-register
Content-Type: application/json

{"user": "test", "password":  "test"}

> {%
 client.assert(typeof response.body.token !== "undefined", "No token returned");
 client.global.set("auth_token", response.body.token)
 %}
